# Change these first
owner: mrsz-innovate # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Dashboard
    url: https://app.eventnexo.co
    icon: https://eventnexo.co/favicon.png
  - name: Eventnexo Website
    url: https://eventnexo.co
    icon: https://eventnexo.co/favicon.png
  - name: Me App
    url: https://eventnexo.me
    icon: https://eventnexo.co/favicon.png
  - name: Backend Api
    url: https://api.eventnexo.co/api
    icon: https://eventnexo.co/favicon.png
assignees: # Users to assign downtime issues (optional)
  - mujhtech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.eventnexo.co
  # baseUrl: /your-repo-name
  logoUrl: https://eventnexo.s3.us-west-1.amazonaws.com/black-logo-beta.png
  name: Eventnexo
  introTitle: "**Eventnexo** is a platform where event creator, community leads can build, grow and scale their events/contests with our infrastructure."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/mrsz-innovate/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
